#use_frameworks!
source 'https://github.com/jackczw/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'CPersonalInfoKit_Example' do
  pod 'CPersonalInfoKit', :path => '../'

  target 'CPersonalInfoKit_Tests' do
    inherit! :search_paths

    
  end
end
